### ISSUE TITLE
Manage Function doesn't work

### ISSUE THREAD

**Issue by Matthack19** [Farmerok/Telegram-Remote-Control-PC#1]
Sorry for the english, but the manage function  doesn't work, so it's difficult to navigate between folders. Thanks in advance because it's a great tool

**Comment by Farmerok** [comment]
HI **[Matthack19](https://github.com/Matthack19)**

Do you mean command `/manage cd`? Thanks for letting me know. In the next version I will fix it and make it more convenient to use!

I'm glad you like this tool🙂

**Comment by Matthack19** [comment]
Yes, the main problem is that when I try to change the current directory like this:

![IMG_3492](https://github.com/user-attachments/assets/08b65b12-f13f-4b17-ab53-f2e781593b85)

the bot replies with an error message like this even though I am 100% sure that the directory is correct. In fact, as you can see, the directory I tried to insert with the manage cd function is nothing more than a part of the current directory

![IMG_3493](https://github.com/user-attachments/assets/a015e0e8-f27c-4a61-b4c9-ece6f4f446e3)

Thanks in advance for this awesome tool

**Comment by Farmerok** [comment]
## Yes, you are right, there was an error, I have already corrected it
![изображение](https://github.com/user-attachments/assets/9d8b3035-ece0-4e7b-a689-64d404b9d490)
## And corrected the information
![изображение](https://github.com/user-attachments/assets/7ef05a97-2214-495d-bf98-7a393ce1f251)

 ## there will be a release soon 🙂
