### ISSUE TITLE
FOLDERS WITH SPACES

### ISSUE THREAD

**Issue by Matthack19** [Farmerok/Telegram-Remote-Control-PC#2]
Sorry if I continue to bother you, the manage cd function now works perfectly, but there is a problem when the name of one of the folder in the directory has a space between words, like “Program Files”. I also tried to put the directory in quotation mark but it doesn’t work.
Thanks for your patience

**Comment by Farmerok** [comment]
**Hi** [Matthack19](https://github.com/Matthack19)

**Thank you for reporting my bug, I fixed it, the next fix will correctly handle paths with spaces** 🙂

![изображение](https://github.com/user-attachments/assets/07dbfd17-3819-476b-a80d-1101e2e096da)

**Comment by Matthack19** [comment]
Now that’s perfect
