### ISSUE TITLE
Problem with space in download

### ISSUE THREAD

**Issue by Matthack19** [Farmerok/Telegram-Remote-Control-PC#3]
Hi, it’s always me, there is the same bug with the file name with spaces in the Download and RenameFl functions, without spaces they work perfecty, but with a space in the name it doesn’t work. Thanks for your patience

**Comment by Farmerok** [comment]
## Greetings [Matthack19](https://github.com/Matthack19)

What exactly is the problem?  
The `/Download` command works; the file downloads even if it has spaces in its name.  
![image](https://github.com/user-attachments/assets/efe2abe2-ac29-4396-b6b4-7e9fec29d1e7)

For the `/RenameFL` command:  
![image](https://github.com/user-attachments/assets/01f7171c-5f22-435b-b26e-b556451ae590)

And everything works perfectly!  
![image](https://github.com/user-attachments/assets/d38fdfea-0460-42cc-8890-939bfc09c6da)

If the problem persists, please provide more information 🙂

**Comment by Farmerok** [comment]
**Perhaps you meant that the file has an extension, such as `fi le s.txt`?**
**I already solved this problem, I just accidentally disabled the dot in the use of symbols**
![изображение](https://github.com/user-attachments/assets/4b4a54c0-0c87-4c09-8a8a-816230d6b174)

**Comment by Matthack19** [comment]
I don’t know because for me in the version 6.6.2 the files with a space in their name don’t work and I’m sure that the filename is right

**Comment by Farmerok** [comment]
If your file name has an extension (.txt, .ini, etc.), then it will not work in 6.6.2, I have an error with the fact that the function prohibits the use of dots, today I will try to download an update that should solve your problem problem

If something else specific does not work, we can discuss it in a telegram, you will show how you do it.

**Comment by Matthack19** [comment]
Thanks with the new update it works fine, but i found a new little problem: when you use the /Scanfolder function and in the directory there are too many files or folders an error messagge like this appears:

![IMG_3530](https://github.com/user-attachments/assets/3d16430e-58bd-431e-8e28-2bac43f14d3c)

I remember that in the previous versions the bot sent you a text file with all the file in the directory.
Thanks for your patience

**Comment by Farmerok** [comment]
### The problem was quickly found and corrected. Thanks for reporting her 🙂

**If you have other problems please let me know**
